version: '3, or 4'
services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      