version: '3, or 4'
services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
      